### PR TITLE
trigger test fail when image sizes are unequal

### PR DESCRIPTION
**Pull request by johnnychen94**

### CODE REVIEW

**Comment by oxinabox** [comment]
LGTM, seems like that should have always been the behavior.
bump patch version so can tag release

**Comment by johnnychen94** [comment]
There're several PRs in plan, I'll bump a version after that.

**Comment by oxinabox** [comment]
Bump version. Change to -DEV.
Per (imo)
https://white.ucc.asn.au/2019/09/28/Continuous-Delivery-For-Julia-Packages.html

**Comment by johnnychen94** [comment]
I'm going to merge this and bump a patch version.

**Pull request merged**
